### ISSUE TITLE
Exporting tekkers

### ISSUE THREAD

**Issue by hdrdavies** [kasaromi/blog#61]
You can export [these functions](https://github.com/kasaromi/blog/blob/3b9e9cdbe58ffeb0e06aea4150b10d0074ad0897/server/redis.js#L60) a little easier by just making them sit on an object, [like so](https://github.com/liberty-x/lxdata/blob/ea799b845cd46910b4a560cbac34d2fa3cf63172/js/app.js#L1). Might make it a bit more readable and saves writing :smile:

**Comment by RobStallion** [comment]
Very handy, thanks @hdrdavies 
Will use next time

**Comment by hdrdavies** [comment]
Happy to help @RobStallion :smile:
