### ISSUE TITLE
page width

### ISSUE THREAD

**Issue by andrewMacmurray** [kasaromi/blog#62]
your page width is being thrown out by your login div and your h1 kasaromi element, make sure these fit within the page so we can't scroll left and right

**Comment by MyPitit** [comment]
Hey @andrewMacmurray you are right. Thanks a lot for your issue. @tormod17 also have raised an issue pointing that problem. https://github.com/kasaromi/blog/issues/63 I'm working on it :)

**Comment by andrewMacmurray** [comment]
@MyPitit  :+1:

**Comment by MyPitit** [comment]
Hi @andrewMacmurray I fix this issue ^^
